export const TODAY = 'today'
export const ARTIZEN_TIMEZONE = 'America/Los_Angeles'
export const HASURA_TIMEZONE_FORMAT = 'YYYY-MM-DDTHH:mm:ss'

export const DEFAULT_GRANT_LENGTH_HOURS = 24
export const DEFAULT_GRANT_GOAL_ETH = 1

export const WALLET_ERROR_UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION'
export const WALLET_ERROR_INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS'
export const WALLET_ERROR_UNPREDICTABLE_GAS_LIMIT = 'UNPREDICTABLE_GAS_LIMIT'
export const WALLET_ERROR_ACTION_REJECTED = 'ACTION_REJECTED'
export const WALLET_CHAIN_MISMATCH = 'Chain mismatch:'
export const WALLET_NO_FOUND = 'err: insufficient funds'

export const PROJECT_LEAD_NOTIFICATION_TEMPLATE_ID = 'RCJRQKDAC04HDVND1HB7B1YMN7PA'
