/* "Why ‘regions’ and not states?
 * DC, and possible territory additions in the future.
 */

const americanRegions = [
  { const: 'AK', title: 'Alaska' },
  { const: 'AL', title: 'Alabama' },
  { const: 'AR', title: 'Arkansas' },
  { const: 'AZ', title: 'Arizona' },
  { const: 'CA', title: 'California' },
  { const: 'CO', title: 'Colorado' },
  { const: 'CT', title: 'Connecticut' },
  { const: 'DC', title: 'District of Columbia' },
  { const: 'DE', title: 'Delaware' },
  { const: 'FL', title: 'Florida' },
  { const: 'GA', title: 'Georgia' },
  { const: 'HI', title: 'Hawaii' },
  { const: 'IA', title: 'Iowa' },
  { const: 'ID', title: 'Idaho' },
  { const: 'IL', title: 'Illinois' },
  { const: 'IN', title: 'Indiana' },
  { const: 'KS', title: 'Kansas' },
  { const: 'KY', title: 'Kentucky' },
  { const: 'LA', title: 'Louisiana' },
  { const: 'MA', title: 'Massachusetts' },
  { const: 'MD', title: 'Maryland' },
  { const: 'ME', title: 'Maine' },
  { const: 'MI', title: 'Michigan' },
  { const: 'MN', title: 'Minnesota' },
  { const: 'MO', title: 'Missouri' },
  { const: 'MS', title: 'Mississippi' },
  { const: 'MT', title: 'Montana' },
  { const: 'NC', title: 'North Carolina' },
  { const: 'ND', title: 'North Dakota' },
  { const: 'NE', title: 'Nebraska' },
  { const: 'NH', title: 'New Hampshire' },
  { const: 'NJ', title: 'New Jersey' },
  { const: 'NM', title: 'New Mexico' },
  { const: 'NV', title: 'Nevada' },
  { const: 'NY', title: 'New York' },
  { const: 'OH', title: 'Ohio' },
  { const: 'OK', title: 'Oklahoma' },
  { const: 'OR', title: 'Oregon' },
  { const: 'PA', title: 'Pennsylvania' },
  { const: 'RI', title: 'Rhode Island' },
  { const: 'SC', title: 'South Carolina' },
  { const: 'SD', title: 'South Dakota' },
  { const: 'TN', title: 'Tennessee' },
  { const: 'TX', title: 'Texas' },
  { const: 'UT', title: 'Utah' },
  { const: 'VA', title: 'Virginia' },
  { const: 'VT', title: 'Vermont' },
  { const: 'WA', title: 'Washington' },
  { const: 'WI', title: 'Wisconsin' },
  { const: 'WV', title: 'West Virginia' },
  { const: 'WY', title: 'Wyoming' },
]

export { americanRegions }
