/* note: location of glyph SVGs is /public/assets/glyphs
 *   enter `yarn generate` and pick iconSet to make file templates
 */

export type GlyphKey = Record<string, string>

export const glyphKey: GlyphKey = {
  arrow: 'arrow',
  badge: 'badge',
  bell: 'bell',
  cake: 'cake',
  calendar: 'calendar',
  certificate: 'certificate',
  coins: 'coins',
  countdown: 'countdown',
  creditCard: 'creditCard',
  cross: 'cross',
  crown: 'crown',
  currencyDollar: 'currencyDollar',
  discord: 'discord',
  dollar: 'dollar',
  donate: 'donate',
  ethereum: 'ethereum',
  face: 'face',
  facebook: 'facebook',
  gear: 'gear',
  github: 'github',
  glob: 'globe',
  hamburger: 'hamburger',
  info: 'info',
  infoLarge: 'infoLarge',
  instagram: 'instagram',
  intersect: 'intersect',
  lock: 'lock',
  mathMinus: 'mathMinus',
  mathPlus: 'mathPlus',
  party: 'party',
  palette: 'palette',
  phone: 'phone',
  plane: 'plane',
  polygon: 'polygon',
  power: 'power',
  refresh: 'refresh',
  swap: 'swap',
  tag: 'tag',
  tick: 'tick',
  token: 'token',
  trend: 'trend',
  twitter: 'twitter',
  usdCoin: 'usdCoin',
  wallet: 'wallet',
}
