export type GlyphKey = Record<string, string>

export const glyphKey: GlyphKey = {
  arrow: 'arrow',
  badge: 'badge',
  bell: 'bell',
  cake: 'cake',
  calendar: 'calendar',
  certificate: 'certificate',
  countdown: 'countdown',
  cross: 'cross',
  currencyDollar: 'currencyDollar',
  discord: 'discord',
  donate: 'donate',
  ethereum: 'ethereum',
  face: 'face',
  facebook: 'facebook',
  gear: 'gear',
  github: 'github',
  hamburger: 'hamburger',
  info: 'info',
  infoLarge: 'infoLarge',
  lock: 'lock',
  mathMinus: 'mathMinus',
  mathPlus: 'mathPlus',
  party: 'party',
  palette: 'palette',
  plane: 'plane',
  polygon: 'polygon',
  power: 'power',
  tag: 'tag',
  tick: 'tick',
  token: 'token',
  trend: 'trend',
  twitter: 'twitter',
  usdCoin: 'usdCoin',
  wallet: 'wallet',
}
