name: 'Playwright Tests PR test'
on: [pull_request]
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn
      - name: Run yarn build
        env:
          NEXT_PUBLIC_HASURA_GRAPHQL_URL: ${{ secrets.NEXT_PUBLIC_HASURA_GRAPHQL_URL }}
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
        run: yarn build
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: run playwright tests
        run: yarn test:e2e
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
